Pacer.Web/Models/TrainingPlan/EditTargetTimeViewModel.cs
using Pacer.Data.Entities;

public class EditTargetTimeViewModel
{
    public int TrainingPlanId { get; set; }
    public RaceType TargetRace { get; set; }
    public TimeSpan TargetTime { get; set; }
}

Pacer.Web/Models/TrainingPlan/TrainingPlanCalendarViewModel.cs
using Pacer.Data.Entities;
using Pacer.Web;
using Pacer.Web.Models.TrainingPlan;

public class TrainingPlanCalendarViewModel
{
    public int Id { get; set; }
    public RaceType TargetRace { get; set; }
    public string TargetRaceDisplayName => TargetRace.GetDisplayName();
    public string TargetTime { get; set; }
    public string TargetPace { get; set; }
    public DateTime RaceDate { get; set; }    
    public int Month  { get; set; }
    public int Year { get; set; }
    public List<WorkoutViewModel> Workouts { get; set; }
    public List<WeekDistance> WeekDistances { get; set; }

}

Pacer.Web/Models/TrainingPlan/TrainingPlanCreateModel.cs
using System;
using Pacer.Data.Entities;
using System.ComponentModel.DataAnnotations;

public class TrainingPlanCreateModel
{
    [Required]
    public int RunningProfileId { get; set; }

    [Required]
    public RaceType TargetRace { get; set; }
    
    public string[] Recommendation { get; set; }

    [Required]
    [DataType(DataType.Date)]
    public DateTime RaceDate { get; set; }

    [Required]
    [DataType(DataType.Time)]
    public TimeSpan TargetTime { get; set; }
    
    public TimeSpan EstimatedMarathonTime { get; set; }
    
    public TimeSpan EstimatedHalfMarathonTime { get; set; }
}

Pacer.Web/Models/TrainingPlan/TrainingPlanDeleteModel.cs
using System;
using Pacer.Data.Entities;
using System.ComponentModel.DataAnnotations;

public class TrainingPlanDeleteModel
{
    [Required]
    public int Id { get; set; }

    [Required]
    public RaceType TargetRace { get; set; }

    [Required]
    [DataType(DataType.Date)]
    public DateTime RaceDate { get; set; }

    [Required]
    [DataType(DataType.Time)]
    public TimeSpan TargetTime { get; set; }
}

Pacer.Web/Models/TrainingPlan/TrainingPlanViewModel.cs
using Pacer.Data.Entities;
using Pacer.Web;

public class TrainingPlanViewModel
{
    public int Id { get; set; }
    public RaceType TargetRace { get; set; }
    public DateTime RaceDate { get; set; }
    public string TargetRaceDisplayName => TargetRace.GetDisplayName();
    public string TargetTime { get; set; }
    public string TargetPace { get; set; }
    public IList<WeekViewModel> Weeks { get; set; }
}
public class WeekViewModel
{
    public int WeekNumber { get; set; }
    public IList<WorkoutViewModel> Workouts { get; set; }
}

Pacer.Web/Models/TrainingPlan/TutorialViewModel.cs
using Pacer.Data.Entities;
using Pacer.Web;

public class TutorialViewModel
{
    public int Id { get; set; }
    public RaceType TargetRace { get; set; }

}

Pacer.Web/Models/TrainingPlan/WeekDistance.cs
namespace Pacer.Web.Models.TrainingPlan;
public class WeekDistance
{
    public int Week { get; set; }
    public double TargetDistance { get; set; }
    public double ActualDistance { get; set; }
    // Used for the progress table
    public double PercentageComplete 
    { 
        get 
        {
            return TargetDistance == 0 ? 0 : (ActualDistance / TargetDistance) * 100;
        }
    }
}

Pacer.Web/Models/TrainingPlan/WorkoutViewModel.cs
using Pacer.Data.Entities;

public class WorkoutViewModel
{
    public int Id { get; set; }
    public WorkoutType Type { get; set; }
    public DateTime Date { get; set; }
    public string DateString => Date.ToString("yyyy-MM-ddTHH:mm:ssZ");
    public string FormattedDate => Date.ToString("yyyy-MM-dd");
    public double TargetDistance { get; set; }
    public string TargetPace { get; set; }
    public string WorkoutDescription { get; set; }
    public double ActualDistance { get; set; }
    public TimeSpan ActualTime { get; set; }
    public string ActualPace { get; set; }
}

Pacer.Web/Controllers/TrainingPlanController.cs
using Microsoft.AspNetCore.Mvc;
using Pacer.Data.Entities;
using Pacer.Data.Services;
using Pacer.Web.Models.TrainingPlan;
using System.Globalization;
using System.Security.Claims;
using System.Text.Json;

namespace Pacer.Web.Controllers;

public class TrainingPlanController : BaseController
{
    private readonly ITrainingPlanService _trainingPlanService;
    private readonly IRunningProfileService _runningProfileService;

    public TrainingPlanController(ITrainingPlanService trainingPlanService, IRunningProfileService runningProfileService, ILogger<TrainingPlanController> logger) : base(logger)
    {
        _trainingPlanService = trainingPlanService;
        _runningProfileService = runningProfileService;
    }
    // Private Training Plan Methods
    // This method is used to get the user ID from the claims.
    private int? GetUserId()
    {
        if (!User.Identity.IsAuthenticated)
        {
            _logger.LogWarning("User is not authenticated.");
            Alert("You need to be logged in to access this page.", AlertType.danger);
            return null;
        }
        if (!int.TryParse(User.FindFirstValue(ClaimTypes.Sid), out var userId))
        {
            _logger.LogError($"Unable to parse user id from claim. Claim: {JsonSerializer.Serialize(User.Claims)}");
            Alert("Issue with User ID. Please log out then try again", AlertType.danger);
            return null;
        }

        return userId;
    }
    // This method is used to get the Training Plan View Model for the Week List.
    private TrainingPlanViewModel ConstructTrainingPlanViewModel(TrainingPlan trainingPlan, string formattedTargetTime)
    {
        int currentWeek = 1;
        var viewModel = new TrainingPlanViewModel
        {
            Id = trainingPlan.Id,
            TargetRace = trainingPlan.TargetRace,
            TargetTime = formattedTargetTime,
            TargetPace = trainingPlan.TargetPace,
            RaceDate = trainingPlan.RaceDate,
            Weeks = trainingPlan.Workouts.GroupBy(w => w.Date.GetWeekStartingMonday())
                             .Select(g => new WeekViewModel
                             {
                                 WeekNumber = currentWeek++,
                                 Workouts = g.Select(w => new WorkoutViewModel
                                 {
                                     Id = w.Id,
                                     Type = w.Type,
                                     Date = w.Date,
                                     TargetDistance = w.TargetDistance,
                                     TargetPace = LookupTargetPaceForWorkout(w.Type, trainingPlan.Paces),
                                     ActualDistance = w.ActualDistance,
                                     ActualTime = w.ActualTime,
                                     ActualPace = w.ActualDistance > 0 ? TimeSpan.FromMinutes(w.ActualTime.TotalMinutes / w.ActualDistance).ToString(@"mm\:ss") : null,
                                     WorkoutDescription = w.WorkoutDescription
                                 }).ToList()
                             }).ToList()
        };
        return viewModel;
    }
    // This method is used to get the Training Plan Calendar View Model.
    private TrainingPlanCalendarViewModel GetTrainingPlanCalendarViewModel()
    {
        var userId = User.FindFirstValue(ClaimTypes.Sid);
        if (string.IsNullOrEmpty(userId))
        {
            _logger.LogWarning("User ID (Sid claim) is not set.");
            return null;
        }

        if (!int.TryParse(userId, out int parsedUserId))
        {
            _logger.LogError($"Failed to parse User ID: {userId}");
            return null;
        }

        var trainingPlan = _trainingPlanService.GetPlanByUserId(parsedUserId);
        if (!ValidateTrainingPlan(trainingPlan))
        {
            return null;
        }

        var firstWorkoutDate = GetFirstWorkoutDate(trainingPlan);
        var formattedTargetTime = FormatTargetTime(trainingPlan.TargetTime);

        var workouts = CreateWorkoutViewModels(trainingPlan);

        return new TrainingPlanCalendarViewModel
        {
            Id = trainingPlan.Id,
            TargetTime = formattedTargetTime,
            Month = firstWorkoutDate.Month,
            Year = firstWorkoutDate.Year,
            RaceDate = trainingPlan.RaceDate,
            TargetRace = trainingPlan.TargetRace,
            TargetPace = trainingPlan.TargetPace,
            Workouts = workouts
        };
    }
    // This method is used to get the first workout date.
    private DateTime GetFirstWorkoutDate(TrainingPlan trainingPlan)
    {
        return trainingPlan.Workouts.OrderBy(w => w.Date).First().Date;
    }
    // This method is used to format the target time.
    private string FormatTargetTime(TimeSpan targetTime)
    {
        return targetTime.ToString(@"h\:mm");
    }
    // This method is used to create the workout view models.
    private List<WorkoutViewModel> CreateWorkoutViewModels(TrainingPlan trainingPlan)
    {
        return trainingPlan.Workouts.Select(w => new WorkoutViewModel
        {
            Id = w.Id,
            Type = w.Type,
            Date = w.Date,
            TargetDistance = w.TargetDistance,
            ActualDistance = w.ActualDistance,
            TargetPace = LookupTargetPaceForWorkout(w.Type, trainingPlan.Paces),
            ActualTime = w.ActualTime,
            ActualPace = w.ActualDistance > 0 ? TimeSpan.FromMinutes(w.ActualTime.TotalMinutes / w.ActualDistance).ToString(@"mm\:ss") : null
        }).ToList();
    }
    // This method is used to lookup the target pace for a workout.
    private string LookupTargetPaceForWorkout(WorkoutType type, ICollection<TrainingPlanPace> paces)
    {
        var minPace = paces.FirstOrDefault(p => p.WorkoutType == type && p.PaceType == PaceType.Min)?.PaceString;
        var maxPace = paces.FirstOrDefault(p => p.WorkoutType == type && p.PaceType == PaceType.Max)?.PaceString;

        // If both paces are available, return a range.
        if (minPace != null && maxPace != null)
        {
            return $"{minPace} - {maxPace}";
        }
        // Otherwise, return whichever is available, or null if neither are.
        return minPace ?? maxPace;
    }
    // This method is used to validate the training plan.
    private bool ValidateTrainingPlan(TrainingPlan trainingPlan)
    {
        if (trainingPlan == null)
        {
            _logger.LogError("Training plan not found.");
            Alert("Error: Training plan not found", AlertType.danger);
            return false;
        }
        if (trainingPlan.Workouts == null)
        {
            _logger.LogError("Training plan has null workouts.");
            Alert("Error: Training plan has null workouts", AlertType.danger);
            return false;
        }
        if (!trainingPlan.Workouts.Any())
        {
            _logger.LogError("Training plan has no workouts.");
            Alert("Error: Training plan has no workouts", AlertType.danger);
            return false;
        }
        return true;
    }

    // Controller Endpoints
    // This is the GET route for the Training Plan Index page.
    [HttpGet]
    public IActionResult Index()
    {
        var userId = GetUserId();
        if (userId == null)
        {
            return RedirectToAction("Login", "User");
        }
        var runningProfile = _runningProfileService.GetProfileByUserId(userId.Value);
        if (runningProfile == null)
        {
            TempData["Alert.Message"] = "Please Create a running profile";
            TempData["Alert.Type"] = "info";
            return RedirectToAction("CreateProfile", "Profile");
        }
        var trainingPlan = _trainingPlanService.GetPlanByUserId(userId.Value);

        if (trainingPlan != null)
        {
            return RedirectToAction("ViewTrainingPlan");
        }

        return RedirectToAction("Disclaimer");
    }
    // This is the GET route for the Disclaimer page.
    [HttpGet]
    public IActionResult Disclaimer()
    {
        return View();
    }
    // This is the GET for the Create Training Plan page.
    [HttpGet]
    public IActionResult CreateTrainingPlan()
    {
        var userId = GetUserId();
        if (userId == null)
        {
            return RedirectToAction("Login", "User");
        }
        var runningProfile = _runningProfileService.GetProfileByUserId(userId.Value);
        if (runningProfile == null)
        {
            TempData["Alert.Message"] = "Error: Running Profile not found";
            TempData["Alert.Type"] = "danger";
            return RedirectToAction("Error", "Home");
        }
        var trainingPlan = _trainingPlanService.GetPlanByUserId(userId.Value);
        if (trainingPlan != null)
        {
            TempData["Alert.Message"] = "Error: Training Plan already exists";
            TempData["Alert.Type"] = "danger";
            return RedirectToAction("Index", "TrainingPlan");
        }
        int daysUntilSunday = ((int)DayOfWeek.Sunday - (int)DateTime.Now.DayOfWeek + 7) % 7;
        DateTime suggestedDate = DateTime.Now.Date.AddDays(daysUntilSunday).AddDays(12 * 7); // 12 weeks later

        var model = new TrainingPlanCreateModel
        {
            RunningProfileId = runningProfile.Id,
            Recommendation = _trainingPlanService.GetRecommendation(runningProfile.EstimatedMarathonTime, runningProfile.EstimatedHalfMarathonTime, runningProfile.WeeklyMileage, runningProfile.DateOfBirth, runningProfile.FiveKTime),
            RaceDate = suggestedDate,
            EstimatedMarathonTime = runningProfile.EstimatedMarathonTime,
            EstimatedHalfMarathonTime = runningProfile.EstimatedHalfMarathonTime
        };

        return View(model);
    }
    // This is the POST route for the Create Training Plan page.
    [HttpPost]
    public IActionResult CreateTrainingPlan(TrainingPlanCreateModel model)
    {
        if (ModelState.IsValid)
        {

Pacer.Web/Views/Shared/Components/Tooltip/ToolTipViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

public class TooltipViewComponent : ViewComponent
{
    public Task<IViewComponentResult> InvokeAsync(string key)
    {
        var tooltips = new Dictionary<string, string>
        {
            
            // Running Profile Tooltips
            {"WeeklyMileage", "Please enter how many miles you have ran each week, on average, for the past 4 weeks."},
            {"5KTime", "Please input a recent 5k time. If you don't have one then please time yourself running 5 kilometres, or 3.1 miles."},
            {"CreateProfile","We will analyse this profile to provide you with training plan recommendations. You will be able to edit this information later."},
            {"EditProfile","This updated 5k time will affect the next new training plan you create. If you want to edit your paces for an existing training plan, then please directly edit the target time."},
            
            // Training Plan Tooltips
            {"TrainingPlan", "All paces are given in minutes and seconds per mile. Add workout data to track your training."},
            {"CreateTrainingPlan","The Standard Half Marathon plan will begin at 10 miles a week and the Standard Marathon Plan will begin at 25 miles a week."},
            {"CreateDateofRace","This will update to the length of the selected training plan. Your race should be on this date or later."},
            {"CreateTargetTime","Times are given in hours and minutes. You may edit your target time if you like."},
            {"ChangeDay","Choose a new date for this workout from available days this week."},

            // Workout Type Tooltips
            { "RecoveryRun", "Very easy runs designed to allow your muscles to recover while still getting in some mileage." },
            { "EasyRun", "Runs to build your aerobic base, done at a relaxed pace." },
            { "LongRun", "This is usually the longest run of the week, designed to build up your endurance." },
            { "MarathonPace", "These runs are done at the pace you hope to maintain in your target race." },
            { "IntervalTraining", "These workouts involve periods of high-intensity running interspersed with periods of low-intensity recovery." },
            { "TempoRun", "These runs are done at a 'comfortably hard' pace to help increase your anaerobic threshold." },
            { "VO2Max", "These workouts are as fast as you can go, designed to improve your maximum oxygen uptake, an important measure of aerobic fitness." },
            
            // Weather Tooltips
            {"Timezone", "All displayed times are local to the selected location."},
            {"Weather", "Weather data is provided by OpenWeatherMap."},
            {"CountryCode", "Country codes are checked against ISO 3166-1 alpha-2. Eg. GB = Great Britain, IE = Ireland"}

        };
        tooltips.TryGetValue(key, out var tooltipText);

        // If the key doesn't exist, set a default tooltip text
        tooltipText ??= "Are you enjoying Pacer? Please email us! We would love to hear from you";
        return Task.FromResult((IViewComponentResult)View("Default", tooltipText));

    }
}

Pacer.Web/Views/TrainingPlan/Calendar.cshtml
@model TrainingPlanCalendarViewModel

@{
    var viewModelJson = System.Text.Json.JsonSerializer.Serialize(Model);
}

<div id="calendar-plan" class="card shadow p-5 mt-4 mx-auto w-75">
    <div class="position-absolute top-0 start-50 translate-middle rounded-circle bg-dark">
        <img src="\images\LogoTrimWIP.png" alt="Logo" height="50px">
    </div>
    <a href="@Url.Action("ViewTrainingPlan")" class="btn btn-success">
        <i class="bi bi-list"></i> Week List</a>
    <!-- Training plan header & Details Partials-->
    <partial name="_TrainingPlanHeader" model="Model" />
    <partial name="_DetailsButton" model="Model" />
    <!-- Training plan key -->
    <div class="col-md-12 key">
        <div class="key-item jsCalendar-RecoveryRun">
            Recovery Run @await Component.InvokeAsync("Tooltip", new { key = "RecoveryRun" })
        </div>
        <div class="key-item jsCalendar-EasyRun">
            Easy Run @await Component.InvokeAsync("Tooltip", new { key = "EasyRun" })
        </div>

        <div class="key-item jsCalendar-LongRun">
            Long Run @await Component.InvokeAsync("Tooltip", new { key = "LongRun" })
        </div>
        @if (Model.TargetRace == RaceType.Marathon || Model.TargetRace == RaceType.BMarathon)
        {
            <div class="key-item jsCalendar-MarathonPace">
                Race Pace @await Component.InvokeAsync("Tooltip", new { key = "MarathonPace" })
            </div>
        }
        <div class="key-item jsCalendar-IntervalTraining">
            Interval Training @await Component.InvokeAsync("Tooltip", new { key = "IntervalTraining" })
        </div>
        <div class="key-item jsCalendar-TempoRun">
            Tempo Run @await Component.InvokeAsync("Tooltip", new { key = "TempoRun" })
        </div>
        @if (Model.TargetRace == RaceType.HalfMarathon || Model.TargetRace == RaceType.BHalfMarathon)
        {
            <div class="key-item jsCalendar-VO2Max">
                VO2 Max @await Component.InvokeAsync("Tooltip", new { key = "VO2Max" })
            </div>
        }
    </div>
    <hr class="custom-hr">
    <!-- Calendar -->
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div id="calendar" class="material-theme" data-month-format="month YYYY" data-day-format="DD"></div>
            </div>
            <div class="col-md-6">
                <div id="workout-details" aria-live="polite">
                    <h4 id="workout-date">Click on the dates in the calendar to see your workouts.</h4>
                    <hr class="custom-hr">
                    <h5 id="workout-type"></h5>
                    <h6 id="workout-pace"></h6>
                    <p id="workout-description"></p>
                    <div id="previous-results" style="display: none;">
                        <h4>Workout Complete!</h4>
                        <p id="prev-distance">Distance Ran: </p>
                        <p id="prev-time">Duration: </p>
                        <p id="prev-pace">Pace: </p>
                        <!-- Clear form -->
                        <form id="clear-form" method="post" action="@Url.Action("ClearWorkoutActuals", "TrainingPlan")"
                            onsubmit="return confirmClear();">
                            <input type="hidden" id="clearWorkoutId" name="WorkoutId" value="@Model.Id">
                            <input type="hidden" name="returnUrl" value="Calendar" />
                            <button type="submit">Clear</button>
                        </form>
                    </div>
                    <!-- Entry form -->
                    <form id="entry-form" method="post" style="display: none;"
                        action="@Url.Action("SaveWorkoutActuals", "TrainingPlan")">
                        <input type="hidden" id="workoutId" name="WorkoutId" value="@Model.Id">
                        <input type="hidden" name="returnUrl" value="Calendar" />
                        <div>
                            <label for="actualDistance">
                                <h5>Actual Distance Ran:</h5>
                            </label>
                        </div>
                        <div class="mb-1">
                            <input type="number" id="actualDistance" name="ActualDistance" min="0" max="50" required
                                aria-label="Actual Distance">
                            miles
                        </div>
                        <div>
                            <label for="actualTime">
                                <h5>Actual Duration:</h5>
                            </label>
                            <div style="display: flex; justify-content: space-between; max-width: 200px;">
                                <div>
                                    <label for="actualHours">Hours:</label>
                                    <input type="number" id="actualHours" name="ActualHours" min="0" max="6" required
                                        value="0" aria-label="Actual Distance">
                                </div>
                                <div>
                                    <label for="actualMinutes">Minutes:</label>
                                    <input type="number" id="actualMinutes" name="ActualMinutes" min="0" max="59"
                                        required value="0">
                                </div>
                                <div>
                                    <label for="actualSeconds">Seconds:</label>
                                    <input type="number" id="actualSeconds" name="ActualSeconds" min="0" max="59"
                                        required value="0">
                                </div>
                            </div>
                        </div>
                        <div>
                            <span id=warningField></span>
                        </div>
                        <button type="submit" class="loading-button">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Mileage graph -->
<partial name="_MileageGraph" model="@Model.WeekDistances" />

<script src="https://unpkg.com/simple-jscalendar@1.4.4/source/jsCalendar.min.js"></script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        var viewModel = @Html.Raw(viewModelJson);
        var targetRaceDisplayName = '@Model.TargetRaceDisplayName';
        var targetTime = '@Model.TargetTime';
        var targetPace = '@Model.TargetPace';
    </script>
    <script src="~/js/calendar.js"></script>
}

Pacer.Web/Views/TrainingPlan/CreateTrainingPlan.cshtml
@model TrainingPlanCreateModel

<div class="card shadow p-4 mt-4 mx-auto w-75">
    <div class="position-absolute top-0 start-50 translate-middle rounded-circle bg-dark">
        <img src="\images\LogoTrimWIP.png" height="50px">
    </div>
    <h1 class="mx-auto">Create Training Plan</h1>
    <!-- Form to create a training plan -->
    <form asp-action="CreateTrainingPlan" asp-controller="TrainingPlan" method="post" role="form">

        <input type="hidden" asp-for="RunningProfileId" />

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="mt-3 text-center">
            <p>Beginner Training Plans are designed to carefully build up your mileage and are less demanding overall
                than Standard Plans.</p>
            <p>You will be more likely to hit your target time if you complete a Standard plan instead of
                Beginner.</p>
            <p>Half-Marathon training plans last for twelve weeks, while Marathon training plans last for sixteen weeks.
            </p>
        </div>
        <hr class="custom-hr">
        <!-- Recommendations based on running profile-->
        <div class="mt-3 text-center">
            @foreach (var recommendationPart in Model.Recommendation)
            {
                <p><b>@recommendationPart</b></p>
            }
        </div>
        <hr class="custom-hr">
        <div class="mt-3">
            <label asp-for="TargetRace" class="form-label" id="raceTypeLabel">Training Plan 
                @await Component.InvokeAsync("Tooltip", new {key = "CreateTrainingPlan" })</label>
            <select id="raceTypeDropdown" asp-for="TargetRace" asp-items="Html.GetEnumSelectList<RaceType>()"
                class="form-control" aria-labelledby="raceTypeLabel" onchange="updateTargetDate();"></select>
            <span asp-validation-for="TargetRace" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="RaceDate" class="form-label" id="raceDateLabel">Date of Race 
                @await Component.InvokeAsync("Tooltip", new { key = "CreateDateofRace" })</label>
            <input type="date" asp-for="RaceDate" class="form-control" aria-labelledby="raceDateLabel" />
            <span asp-validation-for="RaceDate" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label id="targetTimeLabel" class="form-label"></label>@await Component.InvokeAsync("Tooltip", new { key =
            "CreateTargetTime" })
            <input id="targetTimeInput" type="range" class="form-control" min="60" max="240" step="1"
                aria-labelledby="targetTimeLabel" oninput="displayTime(this.value)" />
            <span id="targetTimeDisplay">@Model.EstimatedHalfMarathonTime.ToString("h\\:mm")</span>
            <span asp-validation-for="TargetTime" class="text-danger"></span>
        </div>

        <input type="hidden" asp-for="TargetTime" id="hiddenTargetTime" />


        <div class="mt-3">
            <button type="submit" class="btn btn-primary btn-block loading-button">
                Create Plan
            </button>
            <a class="btn btn-link ms-3" asp-controller="Home" asp-action="Index">Cancel</a>
        </div>

    </form>
</div>

@{
    var marathonValue = ((int)RaceType.Marathon).ToString();
    var bMarathonValue = ((int)RaceType.BMarathon).ToString();
    var halfMarathonValue = ((int)RaceType.HalfMarathon).ToString();
    var bHalfMarathonValue = ((int)RaceType.BHalfMarathon).ToString();
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/create-training-plan.js" asp-append-version="true"></script>
<!-- Scripts to handle the RaceTime slider and auto-updating of Race Date-->
    <script>
        function displayTime(minutes) {
            // Convert the minutes into a TimeSpan or similar format
            var hours = Math.floor(minutes / 60);
            minutes %= 60;
            var timeString = hours + ":" + (minutes < 10 ? "0" : "") + minutes;

            document.getElementById('targetTimeDisplay').textContent = timeString;

            document.getElementById('hiddenTargetTime').value = timeString;
        }
        function updateTargetDate() {
            var raceTypeDropdown = document.getElementById('raceTypeDropdown');
            var targetTimeSlider = document.getElementById('targetTimeInput');
            var targetTimeLabel = document.getElementById('targetTimeLabel');
            var raceDateInput = document.getElementById('RaceDate');
            var selectedRaceType = raceTypeDropdown.options[raceTypeDropdown.selectedIndex].value;

            var today = new Date();
            var daysUntilSunday = (7 - today.getDay()) % 7;

            if (selectedRaceType === '@marathonValue' || selectedRaceType === '@bMarathonValue') {
                targetTimeSlider.min = 125; // 2 hours 5 minutes in minutes
                targetTimeSlider.max = 300; // 5 hours in minutes
                targetTimeSlider.value = Math.floor('@(Model.EstimatedMarathonTime.TotalMinutes)');
                targetTimeLabel.textContent = 'Marathon Target Time';

                today.setDate(today.getDate() + daysUntilSunday + 16 * 7); // Add 16 weeks to the date
            } else if (selectedRaceType === '@halfMarathonValue' || selectedRaceType === '@bHalfMarathonValue') {
                targetTimeSlider.min = 60; // 1 hour in minutes
                targetTimeSlider.max = 150; // 2.5 hours in minutes
                targetTimeSlider.value = Math.floor('@(Model.EstimatedHalfMarathonTime.TotalMinutes)');
                targetTimeLabel.textContent = 'Half Marathon Target Time';
                today.setDate(today.getDate() + daysUntilSunday + 12 * 7); // Add 12 weeks to the date
            }
            var dateString = today.toISOString().split('T')[0];
            raceDateInput.value = dateString;
            displayTime(targetTimeSlider.value);
        }
        updateTargetDate();

    </script>
}

Pacer.Web/Views/TrainingPlan/_TrainingPlanHeader.cshtml
@using Pacer.Web;
<!-- Training plan header and action buttons -->
<hr class="custom-hr">
<h1 class="my-3 mx-auto">@Model.TargetTime @Model.TargetRaceDisplayName Training Plan 
    @await Component.InvokeAsync("Tooltip", new { key = "TrainingPlan"})</h1>
<h2 class="mx-auto"><a href="@Url.Action("EditTargetTime", new { id = Model.Id })" class="btn btn-warning">
        <i class="bi bi-clock-fill" aria-hidden="true"></i> Edit Target Time</a>
    <a href="@Url.Action("DeleteTrainingPlan", new { id = Model.Id })" class="btn btn-danger">
        <i class="bi bi-trash-fill" aria-hidden="true"></i> Delete Training Plan</a>
    <a href="@Url.Action("Tutorial", new { id = Model.Id })" class="btn btn-secondary">
        <i class="bi bi-lightbulb-fill" aria-hidden="true"></i> Understanding Your Workouts</a></h2>