Pacer.Web/Views/Shared/Components/NavBar/NavbarViewComponent.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Pacer.Data.Services;

namespace Pacer.Web.Components;

public class NavbarViewComponent : ViewComponent
{
    private readonly IUserService _svc;

    public NavbarViewComponent(IUserService svc)
    {
        _svc = svc;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var userEmail = HttpContext.User.FindFirstValue(ClaimTypes.Email);
        var user = await _svc.AsyncGetUserByEmail(userEmail);

        var navbarViewModel = new NavbarViewModel
        {
            User = user,
        };

        return View(navbarViewModel);
    }

}

Pacer.Web/Views/Shared/Components/Paginator/PaginatorViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Pacer.Web.Views.Shared.Components;

[ViewComponent]
public class PaginatorViewComponent : ViewComponent
{
    
    public IViewComponentResult Invoke(string action, int rows, int pages, int current, int size=10)
    {       
        // extract existing query parameters except for page and size (these will be replaced with updated values)
        var existingParams = Request.Query
            .Where(e => e.Key.ToLower() != "page" && e.Key.ToLower() != "size")
            .Select(e =>  (e.Key.ToString(),e.Value.ToString())) 
            .ToList();
        
        // build paginator pages (page no and url)
        var pageLinks = new List<Page>();
        for(var p=1; p<=pages;  p++)
        {       
            pageLinks.Add( new Page(p, BuildUrl(action, p, size, existingParams)) ); 
        }

        var props = new PaginatorProps {           
            Pages = pageLinks, 
            CurrentPage = current, 
            TotalRows = rows, 
            PageSize = size,
         };
        return View("Default", props);
    }

    // build a url for action with existing parameters plus updated page and size parameters
    private string BuildUrl(string action, int page, int size, List<(string,string)> existingParameters)
    {
        var paramsDict = new RouteValueDictionary();
        existingParameters.ForEach( p => paramsDict.Add(p.Item1,p.Item2));
        paramsDict.Add("page", page);
        paramsDict.Add("size", size); 
        return Url.Action(action, paramsDict);
    }
}

public record Page(int PageNo, string Url);

public class PaginatorProps 
{
    private int Index => CurrentPage-1; // actual Pages index

    public int CurrentPage { get; set; } // 1..Pages.Count
    public List<Page> Pages { get; set; }
    public int TotalRows { get; set; }
    public int PageSize { get; set; }

    // read-only props
    public int TotalPages => Pages.Count;
    public Page NextPage => HasNextPage ? Pages[Index+1] : null;
    public Page PreviousPage => HasPreviousPage ? Pages[Index-1] : null;
    public Page FirstPage => Pages.FirstOrDefault();
    public Page LastPage => Pages.LastOrDefault();
 
    public bool HasPreviousPage => CurrentPage > 1;
    public bool HasNextPage => CurrentPage < TotalPages;
    public bool AtLastPage => !HasNextPage;
    public bool AtFirstPage => !HasPreviousPage;
}

Pacer.Web/Views/Shared/Components/SortOrder/SortOrderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Pacer.Web.Views.Shared.Components;

[ViewComponent]
public class SortOrderViewComponent : ViewComponent
{

    public IViewComponentResult Invoke(string field="Id", string orderby="Id", string direction = "asc")
    {      
        return View("Default", new SortOrderProps(field.ToLower(), orderby.ToLower(), direction.ToLower()) );
    }
}

public record SortOrderProps(string Field ="Id", string OrderBy="Id", string Direction="asc");

Pacer.Web/Views/Shared/Components/Tooltip/ToolTipViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

public class TooltipViewComponent : ViewComponent
{
    public Task<IViewComponentResult> InvokeAsync(string key)
    {
        var tooltips = new Dictionary<string, string>
        {
            
            // Running Profile Tooltips
            {"WeeklyMileage", "Please enter how many miles you have ran each week, on average, for the past 4 weeks."},
            {"5KTime", "Please input a recent 5k time. If you don't have one then please time yourself running 5 kilometres, or 3.1 miles."},
            {"CreateProfile","We will analyse this profile to provide you with training plan recommendations. You will be able to edit this information later."},
            {"EditProfile","This updated 5k time will affect the next new training plan you create. If you want to edit your paces for an existing training plan, then please directly edit the target time."},
            
            // Training Plan Tooltips
            {"TrainingPlan", "All paces are given in minutes and seconds per mile. Add workout data to track your training."},
            {"CreateTrainingPlan","The Standard Half Marathon plan will begin at 10 miles a week and the Standard Marathon Plan will begin at 25 miles a week."},
            {"CreateDateofRace","This will update to the length of the selected training plan. Your race should be on this date or later."},
            {"CreateTargetTime","Times are given in hours and minutes. You may edit your target time if you like."},
            {"ChangeDay","Choose a new date for this workout from available days this week."},

            // Workout Type Tooltips
            { "RecoveryRun", "Very easy runs designed to allow your muscles to recover while still getting in some mileage." },
            { "EasyRun", "Runs to build your aerobic base, done at a relaxed pace." },
            { "LongRun", "This is usually the longest run of the week, designed to build up your endurance." },
            { "MarathonPace", "These runs are done at the pace you hope to maintain in your target race." },
            { "IntervalTraining", "These workouts involve periods of high-intensity running interspersed with periods of low-intensity recovery." },
            { "TempoRun", "These runs are done at a 'comfortably hard' pace to help increase your anaerobic threshold." },
            { "VO2Max", "These workouts are as fast as you can go, designed to improve your maximum oxygen uptake, an important measure of aerobic fitness." },
            
            // Weather Tooltips
            {"Timezone", "All displayed times are local to the selected location."},
            {"Weather", "Weather data is provided by OpenWeatherMap."},
            {"CountryCode", "Country codes are checked against ISO 3166-1 alpha-2. Eg. GB = Great Britain, IE = Ireland"}

        };
        tooltips.TryGetValue(key, out var tooltipText);

        // If the key doesn't exist, set a default tooltip text
        tooltipText ??= "Are you enjoying Pacer? Please email us! We would love to hear from you";
        return Task.FromResult((IViewComponentResult)View("Default", tooltipText));

    }
}

Pacer.Web/Views/Shared/_Alert.cshtml
<!-- AMC - alert partial to display any alerts via layout pacer -->
@{
    var message = TempData["Alert.Message"] ?? null;
    var type    = TempData["Alert.Type"]    ?? null;
}
@if (message != null)
{
    <div class="alert alert-@type alert-dismissible fade show" role="alert">
        @message
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

Pacer.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Pacer</title>
    <link rel="shortcut icon" type="image/x-icon" href="/images/LogoTrimWIP.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>

<body>
    <header role="banner">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-lg rounded mb-3" role="navigation"
            aria-label="Main navigation">
            <div class="container">
                <a class="navbar-brand" href="#" style="display: flex; align-items: center;">
                    <svg xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Pacer Logo" width="30" height="30"
                        class="bi bi-exclude" viewBox="0 0 40 40" style="margin-right: 5px;">
                        <image xlink:href="/images/LogoTrimWIP.png" width="50" height="50" />
                    </svg>
                    <span>Pacer</span>
                </a>
                @await Component.InvokeAsync("Navbar")
                <partial name="_LoginPartial" />
            </div>
            </div>
        </nav>
    </header>
    <div class="wrapper">
        <div class="container">
            <partial name="_Alert" />
            <main role="main" aria-label="Main Content" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    @{
        var controller = ViewContext.RouteData.Values["controller"].ToString();
        var action = ViewContext.RouteData.Values["action"].ToString();
    }

    @if (!(controller == "Home" && action == "Index"))
    {
        <footer class="sticky-footer border-top footer text-muted">
            <div class="container d-flex justify-content-between align-items-center">
                <div>
                    &copy; @DateTime.Now.Year - Pacer -
                    <a asp-controller="Home" asp-action="Privacy" style="color: inherit;">Privacy</a> -
                    <a asp-controller="Home" asp-action="UserGuide" style="color: inherit;">User Guide</a>
                </div>
                <div>
                    <a href="mailto:feedback.pacer@outlook.com" style="color: inherit;">
                        <i class="bi bi-envelope-fill" aria-hidden="true"></i> Send Feedback
                    </a>
                </div>
            </div>
        </footer>
    }
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>